### ISSUE TITLE
Token失效时间

### ISSUE THREAD

**Issue by Snowfall99** [Snowfall99/jtrace-backend#12]
- [x] 取消token失效时间，将其设置为无限长，目前为固定值720000ms

**Comment by Tongzhixin** [comment]
我阅读了源码，过期时间的主要使用地点在
![图片](https://user-images.githubusercontent.com/48273641/117567117-20440b00-b0ed-11eb-9126-89fe630a2ec7.png)
源码地址：https://github.com/louislivi/fastdep/blob/87ca236d28fa6deaa774ba6b0a5ac3a953120f6d/fastdep-shiro-jwt/src/main/java/com/louislivi/fastdep/shirojwt/jwt/JwtUtil.java#L84
从这个地方可以得知其类型，是个Long类型
https://github.com/louislivi/fastdep/blob/87ca236d28fa6deaa774ba6b0a5ac3a953120f6d/fastdep-shiro-jwt/src/main/java/com/louislivi/fastdep/shirojwt/FastDepShiroJwtProperties.java#L105
然后我尝试重写这个类，虽然没有报错，但是打包运行后在服务器上报错，所以我目前仅仅将其设置为2100000000ms接近一个月。
