### ISSUE TITLE
似乎返回的在线状态status永远是0（离线）

### ISSUE THREAD

**Issue by Waynezee** [Snowfall99/jtrace-backend#57]
使用的是 test2 和 tongzhixin两个账户进行的测试

**Comment by Snowfall99** [comment]
创建websocket连接之后状态才会更改，因为我认为登陆后就应该建立连接，因为如果不能建立连接的话发消息也没办法正常接收

**Comment by Waynezee** [comment]
现在就是登陆后就连接

**Comment by Snowfall99** [comment]
但是login之后也会更新状态为true啊，这个我试过的

**Comment by Snowfall99** [comment]
缓存机制出现问题，删除user上的部分缓存操作进行修复
