### ISSUE TITLE
如果后端返回的信息只有某个对象的主键的话，那前端反复请求可能会加大后端压力

### ISSUE THREAD

**Issue by RidiculousDoge** [Snowfall99/jtrace-backend#61]
（仅仅是一个想到的优化点）
比如说请求messageDetail，comments里面每个comment只有author对象的主键（id），就需要再请求一次username，感觉对服务器压力挺大的。。。

**Comment by Snowfall99** [comment]
所以有什么好的解决想法吗？

**Comment by Snowfall99** [comment]
在后端查询用户名并返回

**Comment by RidiculousDoge** [comment]
> 所以有什么好的解决想法吗？

今天问了问业界究竟是怎么做的，大概是后端优化数据库缓存等等+一次性返回全部信息。（虽然返回内容多但响应时间也可以接受）
不过如果需要执行链接查询这个大概就不行了
and好文分享https://www.cnblogs.com/LBSer/p/4753112.html
